### ISSUE TITLE
Awesome little app

### ISSUE THREAD

**Issue by salgadoma** [eugene-mobile/testjs#1]
Thanks for the useful Pebble app!  Quick question/request:  Have you thought of modifying to allow toggling between multiple Ecobee's?

In my case, you app always defaults to the first (alphabetic) thermostat in the group.

And maybe I missed the "documentation" on how to use, but was able to figure out the "button" flow-chart through trial and error. 

Thanks!

**Comment by eugene-mobile** [comment]
Yes, there is no option to change between multiple thermostats right now. And you are correct that the application is choosing the first available. Configuring this would be a good addition to the app and I'll definitely think of adding the selection in future releases! Thanks for suggestion!

**Comment by eugene-mobile** [comment]
Hello! 
Multiple thermostat support is now available in the app. Enjoy! :)
