### ISSUE TITLE
Support for PTR

### ISSUE THREAD

**Issue by majorgearhead** [eugene-mobile/testjs#3]
Any way to get support for the Pebble Time Round?

**Comment by eugene-mobile** [comment]
Hi! Great news!
Pebble have just released support for Pebble Time Round in their api: 
https://developer.pebble.com/blog/2016/05/16/Pebble-JS-Round/?mc_cid=4308897646&mc_eid=aac96ae3f7
Wait for updates to come soon!!!

**Comment by eugene-mobile** [comment]
Pebble Time Round support is now added to the app!
