### ISSUE TITLE
Menu Crash

### ISSUE THREAD

**Issue by calexander3** [eugene-mobile/testjs#6]
If you exit the main menu and try to enter again, the app will crash. This is caused by the images on the main window. Its weird but it looks like a memory leak with pebble.js. If you prevent the images from being placed on the window, you can enter and exit the menu indefinitely. I was able to reproduce with a different image on a new pebble.js project.

**Comment by calexander3** [comment]
I removed most of the images in #5 and the crash has stopped occurring. I recreated the dots with the UI.Circle element and I think I got it to look pretty close.

**Comment by eugene-mobile** [comment]
I was testing the merged code, and looks like there are still problems in pebble.js. I see the app crashes when you go into menu for the second time and return back to the main screen. Logs show: 

> [ERROR] ault_handling.c:97: App fault! {4e475ece-7659-4ecf-9cc7-57964455b0ba} PC: 0x4400 LR: 0x80a888f

Is it the same error you see?

**Comment by eugene-mobile** [comment]
Sorry - it was old build that I installed by mistake. I think the changed slider on main menu now works fine and it also looks super-awesome!
